#pragma config(Motor,  port2,           rightShooter,  tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           leftShooter,   tmotorVex393_MC29, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	while(true) {
		if(vexRT[Btn6U] == 1) {
			motor[rightShooter] = 127;
			motor[leftShooter] = 127;
		}
		if(vexRT[Btn6D] == 1) {
			motor[rightShooter] = -127;
			motor[leftShooter] = -127;
		}
		else {
			motor[rightShooter] = 0;
			motor[leftShooter] = 0;
		}
	}
}
